#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -location 1 -xoffset 10 -yoffset 10 -line-padding 6 -columns 1 -width 20 -lines 15 -padding 15 -hide-scrollbar -show-icons -drun-icon-theme -font 'Source Code Pro 10'

